### ISSUE TITLE
Firefox Users Cannot use SIWE

### ISSUE THREAD

**Issue by Sterahi** [spruceid/discourse-siwe-auth#18]
As the title says, users logging in with FireFox are unable to use the sign in with Ethereum plugin. I have no idea what's causing this, some initial attempts to sort this out include: 

- Disabling pop-up protection
- Disabling "Enhanced Tracking Protection" 

This has been tested with multiple wallets & on multiple machines. 

Any help would be wonderful!

**Comment by obstropolos** [comment]
Is this specifically for extension wallets? I tried the plugin on a few forms on firefox - it looks like there's an issue for them but not for WC-based ones.

**Comment by Sterahi** [comment]
I don't have a physical wallet to confirm, in this case I 100% was using a plugin wallet (MetaMask), and I'm almost certain that the other user was also using MetaMask.
