### ISSUE TITLE
plugin is not working 

### ISSUE THREAD

**Issue by pushpinder6805** [spruceid/discourse-siwe-auth#19]
You are specifying the gem rbsecp256k1 in /var/www/discourse/plugins/discourse-siwe-auth/plugin.rb, however it does not exist!
Looked for: /var/www/discourse/plugins/discourse-siwe-auth/gems/2.7.6/specifications/rbsecp256k1-5.1.0.gemspec

**Comment by w4ll3** [comment]
the gem [does exist](https://rubygems.org/gems/rbsecp256k1), can you share the error message you're getting?

**Comment by pushpinder6805** [comment]
This is error from installation 

You are specifying the gem rbsecp256k1 in /var/www/discourse/plugins/discourse-siwe-auth/plugin.rb, however it does not exist!
Looked for: /var/www/discourse/plugins/discourse-siwe-auth/gems/2.7.6/specifications/rbsecp256k1-5.1.0.gemspec

and then ./launcher rebuild fail with message scroll up to see error

**Comment by w4ll3** [comment]
could you share the whole log?

**Comment by pushpinder6805** [comment]
no issue with plugin it is working fine , before_code was not added
