### ISSUE TITLE
Issues signing up / logging in

### ISSUE THREAD

**Issue by waqaarali** [spruceid/discourse-siwe-auth#21]
I installed a fresh installation of Discourse using [https://meta.discourse.org/t/install-discourse-on-ubuntu-for-development/14727](https://meta.discourse.org/t/install-discourse-on-ubuntu-for-development/14727). I am not running Discourse through Docker, I get the following errors after attempting to manually install the plugin and try to sign-up/log-in:

```
GET http://127.0.0.1:4200/discourse-siwe/message?eth_account=0xc5213d21d37f2F9e4c771A02983D9D4044aC7dE8&chain_id=1 500 (Internal Server Error)

ajax-error.js:33 
SyntaxError: Unexpected token 'L', "LoadError "... is not valid JSON

siwe-auth-index.js:41 
TypeError: Cannot destructure property 'message' of '(intermediate value)' as it is undefined.
```

UPDATE:

After inspecting network logs I noticed that it couldn't read/find ```rbsecp256k1``` so I have tried to install this package now I can no longer run **bundle install** and I get the error below:

```
/home/user/.rbenv/versions/3.1.3/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:2277:in `check_version_conflict': can't activate rbsecp256k1-5.1.0, already activated rbsecp256k1-5.1.
```

**Comment by waqaarali** [comment]
The ```plugin.rb``` needs to be updated to use the latest version of ```rbsecp256k1``` which is currently 5.1.1

**Comment by jtgi** [comment]
Hit same issue. Opened: https://github.com/spruceid/discourse-siwe-auth/pull/22
